### ISSUE TITLE
failed to decode json webhook payload: unexpected end of JSON input

### ISSUE THREAD

**Issue by mortaelth** [mwennrich/alertlogger#12]
alertlogger panics when parsing the input from alertmanager. Seems like the json format has changed.

```
2024/07/08 11:22:58 http: panic serving 127.0.0.1:51558: failed to decode json webhook payload: unexpected end of JSON input
goroutine 25 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x6625e0, 0xc000064080})
	/usr/local/go/src/runtime/panic.go:890 +0x263
main.main.func1({0x77c77b73b?, 0xffffffffffffffff?}, 0x0?)
	/app/alertlogger.go:114 +0x105
net/http.HandlerFunc.ServeHTTP(0xc0000ee400?, {0x710bd0?, 0xc00018a1c0?}, 0x40d02a?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x710bd0, 0xc00018a1c0}, 0xc0000f8300)
	/usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc0000a12f0?}, {0x710bd0, 0xc00018a1c0}, 0xc0000f8300)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0000f4630, {0x710d98, 0xc0000a0d80})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

looking at the spec at https://prometheus.io/docs/alerting/latest/notifications/, I noticed that "Fingerprint" field was added to alert object, and in the alertGroup, there is no "version" or "groupKey" as defined here:
https://github.com/mwennrich/alertlogger/blob/becff80e4b6191fa5c027c13b22b2f046b6bcc42/alertlogger.go#L16

**Comment by mortaelth** [comment]
sorry, invalid - missing network policy, alertmanager could not connect and the logs above are from manual portforward with invalid data in the request
